// 자치구 → KMA 격자 좌표 (대표 1포인트)
export const SEOUL_GRID: Record<string, { gu_ko: string; nx: number; ny: number }> = {
  "Jongno-gu":      { gu_ko: "종로구",   nx: 60, ny: 127 },
  "Jung-gu":        { gu_ko: "중구",     nx: 60, ny: 127 },
  "Yongsan-gu":     { gu_ko: "용산구",   nx: 60, ny: 126 },
  "Seongdong-gu":   { gu_ko: "성동구",   nx: 61, ny: 127 },
  "Gwangjin-gu":    { gu_ko: "광진구",   nx: 62, ny: 126 },
  "Dongdaemun-gu":  { gu_ko: "동대문구", nx: 61, ny: 127 },
  "Jungnang-gu":    { gu_ko: "중랑구",   nx: 62, ny: 128 },
  "Seongbuk-gu":    { gu_ko: "성북구",   nx: 61, ny: 127 },
  "Gangbuk-gu":     { gu_ko: "강북구",   nx: 61, ny: 128 },
  "Dobong-gu":      { gu_ko: "도봉구",   nx: 61, ny: 129 },
  "Nowon-gu":       { gu_ko: "노원구",   nx: 61, ny: 129 },
  "Eunpyeong-gu":   { gu_ko: "은평구",   nx: 59, ny: 127 },
  "Seodaemun-gu":   { gu_ko: "서대문구", nx: 59, ny: 127 },
  "Mapo-gu":        { gu_ko: "마포구",   nx: 59, ny: 127 },
  "Yangcheon-gu":   { gu_ko: "양천구",   nx: 58, ny: 126 },
  "Gangseo-gu":     { gu_ko: "강서구",   nx: 58, ny: 126 },
  "Guro-gu":        { gu_ko: "구로구",   nx: 58, ny: 125 },
  "Geumcheon-gu":   { gu_ko: "금천구",   nx: 59, ny: 124 },
  "Yeongdeungpo-gu":{ gu_ko: "영등포구", nx: 58, ny: 126 },
  "Dongjak-gu":     { gu_ko: "동작구",   nx: 59, ny: 125 },
  "Gwanak-gu":      { gu_ko: "관악구",   nx: 59, ny: 125 },
  "Seocho-gu":      { gu_ko: "서초구",   nx: 61, ny: 125 },
  "Gangnam-gu":     { gu_ko: "강남구",   nx: 61, ny: 126 },
  "Songpa-gu":      { gu_ko: "송파구",   nx: 62, ny: 126 },
  "Gangdong-gu":    { gu_ko: "강동구",   nx: 62, ny: 126 },
};
