/**
 * Translate Korean bike-share station names to English via Solar Pro 2 and emit
 * a generated TS dict that the web app merges with the hand-curated overrides.
 *
 * Reads `_workspace/02_analytics/popular_stations.json` (falls back to
 * `apps/mobile/assets/data/popular_stations.json`), finds station_no's whose
 * Korean name isn't already mapped in `apps/web/src/lib/station-names-en.ts`,
 * batches 20 per Solar request, caches at
 * `_workspace/03_curation/translations_stations.json`, and writes the generated
 * dict to `apps/web/src/lib/station-names-en.generated.ts`.
 *
 *   pnpm translate:stations
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import OpenAI from "openai";
import { loadEnv, PATHS } from "../lib/env.ts";

interface Station {
  station_no: string;
  station_name_ko: string;
  gu_ko: string;
  gu_en: string | null;
}

const SYSTEM_PROMPT = `You translate Seoul public bike-share (따릉이) station names into concise English labels for foreign tourists.

Rules:
- Use established English place names: subway stations end with "Station" (e.g. 합정역 → "Hapjeong Station"). Exit numbers like "1번 출구" → "Exit 1".
- Schools: include type (e.g. "Yonsei Univ.", "Daewon Elementary").
- "동" administrative areas → "-dong" (e.g. 망원동 → "Mangwon-dong").
- "근처/앞/옆/뒤" → "Near/Front of/Beside/Behind".
- Keep address-style numbers as-is ("망원동 414-12" → "Mangwon-dong 414-12").
- Max ~70 chars. Title Case for proper nouns, sentence case otherwise.
- Do NOT add the Korean or explanations.`;

const SCHEMA = {
  type: "object" as const,
  properties: {
    items: {
      type: "array",
      items: {
        type: "object",
        properties: {
          station_no: { type: "string" },
          name_en: { type: "string" },
        },
        required: ["station_no", "name_en"],
        additionalProperties: false,
      },
    },
  },
  required: ["items"],
  additionalProperties: false,
};

const BATCH_SIZE = 20;

const STATIONS_WORKSPACE = path.join(PATHS.workspace, "02_analytics/popular_stations.json");
const STATIONS_MOBILE = path.join(PATHS.mobileAssets, "popular_stations.json");
const CACHE_FILE = path.join(PATHS.workspace, "03_curation/translations_stations.json");
const GENERATED_TS = path.join(PATHS.root, "apps/web/src/lib/station-names-en.generated.ts");

async function readStations(): Promise<Station[]> {
  try {
    return JSON.parse(await fs.readFile(STATIONS_WORKSPACE, "utf8")) as Station[];
  } catch {
    return JSON.parse(await fs.readFile(STATIONS_MOBILE, "utf8")) as Station[];
  }
}

async function readCache(): Promise<Record<string, string>> {
  try {
    return JSON.parse(await fs.readFile(CACHE_FILE, "utf8")) as Record<string, string>;
  } catch {
    return {};
  }
}

async function writeCache(cache: Record<string, string>): Promise<void> {
  await fs.mkdir(path.dirname(CACHE_FILE), { recursive: true });
  await fs.writeFile(CACHE_FILE, JSON.stringify(cache, null, 2), "utf8");
}

async function writeGenerated(cache: Record<string, string>): Promise<void> {
  const sortedEntries = Object.entries(cache).sort(([a], [b]) => a.localeCompare(b));
  const body = sortedEntries.map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join("\n");
  const content = `// AUTO-GENERATED by scripts/curation/translate-stations.ts. Do not edit by hand.
// Run \`pnpm translate:stations\` to refresh.
export const STATION_NAMES_EN_GENERATED: Record<string, string> = {
${body}
};
`;
  await fs.writeFile(GENERATED_TS, content, "utf8");
}

async function translateBatch(client: OpenAI, batch: Station[]): Promise<Record<string, string>> {
  const userPayload = JSON.stringify(
    { items: batch.map((s) => ({ station_no: s.station_no, name_ko: s.station_name_ko, gu_ko: s.gu_ko })) },
    null,
    2,
  );
  const res = await client.chat.completions.create({
    model: "solar-pro2",
    messages: [
      { role: "system", content: SYSTEM_PROMPT },
      {
        role: "user",
        content: "Translate each item's name_ko into English. Echo the same station_no.\n\n" + userPayload,
      },
    ],
    max_tokens: 1500,
    response_format: {
      type: "json_schema",
      json_schema: { name: "station_translations", strict: true, schema: SCHEMA },
    },
  });
  const raw = res.choices[0]?.message.content ?? '{"items":[]}';
  const parsed = JSON.parse(raw) as { items: { station_no: string; name_en: string }[] };
  const out: Record<string, string> = {};
  for (const it of parsed.items) out[it.station_no] = it.name_en;
  return out;
}

async function main() {
  const env = await loadEnv();
  const apiKey = process.env.SOLAR_API_KEY || env.SOLAR_API_KEY;
  if (!apiKey) throw new Error("SOLAR_API_KEY missing (.env.local or process.env)");
  const client = new OpenAI({ apiKey, baseURL: "https://api.upstage.ai/v1" });

  const stations = await readStations();
  const cache = await readCache();
  console.log(`Stations: ${stations.length}, cached: ${Object.keys(cache).length}`);
  // Note: hand-curated overrides in apps/web/src/lib/station-names-en.ts win on
  // merge, so it's harmless to translate every station here. Keep it simple
  // and don't duplicate the hand-curated set in this script.
  const work = stations.filter((s) => !cache[s.station_no] && s.station_name_ko);
  console.log(`To translate: ${work.length}`);

  for (let i = 0; i < work.length; i += BATCH_SIZE) {
    const batch = work.slice(i, i + BATCH_SIZE);
    process.stdout.write(`\r  · batch ${Math.floor(i / BATCH_SIZE) + 1}/${Math.ceil(work.length / BATCH_SIZE)} (${batch.length}) `);
    let attempt = 0;
    while (attempt < 3) {
      try {
        const result = await translateBatch(client, batch);
        Object.assign(cache, result);
        await writeCache(cache);
        break;
      } catch (e) {
        attempt++;
        console.warn(`\n  ! batch failed (attempt ${attempt}):`, e instanceof Error ? e.message : e);
        if (attempt >= 3) throw e;
        await new Promise((r) => setTimeout(r, 1500 * attempt));
      }
    }
    await new Promise((r) => setTimeout(r, 700));
  }
  console.log();

  await writeGenerated(cache);
  console.log(`✓ cache ${CACHE_FILE}`);
  console.log(`✓ generated ${GENERATED_TS} (${Object.keys(cache).length} entries)`);
}

main().catch((e) => {
  console.error("✗ translate-stations failed:", e);
  process.exit(1);
});
